-- Insert sample clinics data
insert into public.clinics (name, slug, address, prefecture, city, station, station_line, distance, specialties, phone, rating, review_count, image_url, description, features, payment_methods) values
('東京中央クリニック', 'tokyo-chuo-clinic', '東京都千代田区丸の内1-1-1', '東京都', '千代田区', '東京駅', 'JR山手線', '徒歩3分', ARRAY['内科', '外科'], '03-1234-5678', 4.5, 128, '/general-clinic.jpg', '東京駅から徒歩3分の総合クリニック', ARRAY['土日診療', '夜間診療', 'オンライン診療'], ARRAY['現金', 'クレジットカード', '電子マネー']),
('渋谷皮膚科クリニック', 'shibuya-derma-clinic', '東京都渋谷区道玄坂2-2-2', '東京都', '渋谷区', '渋谷駅', 'JR山手線', '徒歩5分', ARRAY['皮膚科', '美容皮膚科'], '03-2345-6789', 4.8, 256, '/dermatology-clinic.png', '渋谷駅から徒歩5分の皮膚科専門クリニック', ARRAY['女性医師在籍', '予約優先', 'キッズスペース'], ARRAY['現金', 'クレジットカード']),
('新宿デンタルクリニック', 'shinjuku-dental-clinic', '東京都新宿区西新宿3-3-3', '東京都', '新宿区', '新宿駅', 'JR山手線', '徒歩7分', ARRAY['歯科', '矯正歯科'], '03-3456-7890', 4.3, 89, '/dental-clinic.png', '新宿駅から徒歩7分の歯科クリニック', ARRAY['夜間診療', '日曜診療', '駐車場あり'], ARRAY['現金', 'クレジットカード', '電子マネー']),
('品川総合医院', 'shinagawa-general-clinic', '東京都港区高輪4-4-4', '東京都', '港区', '品川駅', 'JR山手線', '徒歩2分', ARRAY['内科', '小児科', '整形外科'], '03-4567-8901', 4.6, 342, '/modern-clinic-exterior.jpg', '品川駅から徒歩2分の総合医院', ARRAY['土日診療', '予約優先', 'バリアフリー'], ARRAY['現金', 'クレジットカード']),
('池袋眼科', 'ikebukuro-eye-clinic', '東京都豊島区南池袋5-5-5', '東京都', '豊島区', '池袋駅', 'JR山手線', '徒歩4分', ARRAY['眼科'], '03-5678-9012', 4.7, 167, '/general-clinic.jpg', '池袋駅から徒歩4分の眼科専門クリニック', ARRAY['コンタクト処方', '日帰り手術', '予約優先'], ARRAY['現金', 'クレジットカード', '電子マネー']),
('横浜みなとクリニック', 'yokohama-minato-clinic', '神奈川県横浜市西区みなとみらい6-6-6', '神奈川県', '横浜市西区', '横浜駅', 'JR東海道線', '徒歩8分', ARRAY['内科', '循環器科'], '045-1234-5678', 4.4, 203, '/modern-clinic-exterior.jpg', '横浜駅から徒歩8分の内科クリニック', ARRAY['オンライン診療', '英語対応', '駐車場あり'], ARRAY['現金', 'クレジットカード']),
('大阪梅田クリニック', 'osaka-umeda-clinic', '大阪府大阪市北区梅田7-7-7', '大阪府', '大阪市北区', '梅田駅', '阪急線', '徒歩3分', ARRAY['内科', '消化器科'], '06-1234-5678', 4.5, 178, '/general-clinic.jpg', '梅田駅から徒歩3分の消化器専門クリニック', ARRAY['土日診療', '予約優先', 'オンライン診療'], ARRAY['現金', 'クレジットカード', '電子マネー']),
('名古屋駅前クリニック', 'nagoya-ekimae-clinic', '愛知県名古屋市中村区名駅8-8-8', '愛知県', '名古屋市中村区', '名古屋駅', 'JR東海道線', '徒歩2分', ARRAY['内科', '呼吸器科'], '052-1234-5678', 4.6, 145, '/modern-clinic-exterior.jpg', '名古屋駅から徒歩2分の呼吸器専門クリニック', ARRAY['夜間診療', '予約優先', 'バリアフリー'], ARRAY['現金', 'クレジットカード'])
on conflict (slug) do nothing;
